version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"  # location of your go.mod file
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "github-actions"
    directory: "/"  # for .github/workflows
    schedule:
      interval: "weekly"
