version: '3.8'

services:
  k8s-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: k8s-mcp-server:latest
    container_name: k8s-mcp-server
    ports:
      - "8080:8080"
    volumes:
      - ${HOME}/.kube:/root/.kube
    environment:
      - KUBECONFIG=/root/.kube/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
